#ifndef TEST_SUITES_H
#define TEST_SUITES_H

void run_decode_tests(void);
void run_alu_tests(void);
void run_shift_tests(void);
void run_move_tests(void);
void run_loadstore_tests(void);
void run_memory_tests(void);
void run_flash_mmu_tests(void);
void run_efuse_tests(void);
void run_target_gpio_tests(void);
void run_io_mux_tests(void);
void run_rtc_cntl_tests(void);
void run_rtc_io_tests(void);
void run_sens_tests(void);
void run_apb_saradc_tests(void);
void run_radio_tests(void);
void run_esp32s3_extmem_tests(void);
void run_system_clock_tests(void);
void run_sandbox_input_tests(void);
void run_systimer_tests(void);
void run_timer_group_target_tests(void);
void run_rmt_v1_tests(void);
void run_ledc_v1_tests(void);
void run_usb_serial_jtag_tests(void);
void run_spi_mem_tests(void);
void run_firmware_scan_tests(void);
void run_loader_tests(void);
void run_target_tests(void);
void run_rom_elf_tests(void);
void run_branch_tests(void);
void run_loop_tests(void);
void run_integration_tests(void);
void run_window_tests(void);
void run_guest_call_tests(void);
void run_exception_tests(void);
void run_boolean_tests(void);
void run_mac16_tests(void);
void run_fp_ldst_tests(void);
void run_fp_arith_tests(void);
void run_peripheral_tests(void);
void run_sx127x_tests(void);
void run_axp192_tests(void);
void run_ublox_gps_tests(void);
void run_crypto_tests(void);
void run_wifi_stub_tests(void);
void run_bt_stub_tests(void);
void run_rom_stub_tests(void);
void run_debug_tests(void);
void run_memory_map_tests(void);
void run_freertos_tests(void);
void run_esp_timer_tests(void);
void run_firmware_compat_tests(void);
#ifdef FLEXE_HAS_JIT
void run_jit_tests(void);
#endif

#endif /* TEST_SUITES_H */
